In [146]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [147]:
df=pd.read_csv("cardekho_imputated.csv")

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [149]:
df.columns=df.columns.str.strip()

In [150]:
df.describe()

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,9811.857699,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,5643.418542,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4906.500000,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9872.000000,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,14668.500000,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [151]:
df.head(5)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [152]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [153]:
df['car_name'].unique()

array(['Maruti Alto', 'Hyundai Grand', 'Hyundai i20', 'Ford Ecosport',
       'Maruti Wagon R', 'Hyundai i10', 'Hyundai Venue', 'Maruti Swift',
       'Hyundai Verna', 'Renault Duster', 'Mini Cooper', 'Maruti Ciaz',
       'Mercedes-Benz C-Class', 'Toyota Innova', 'Maruti Baleno',
       'Maruti Swift Dzire', 'Volkswagen Vento', 'Hyundai Creta',
       'Honda City', 'Mahindra Bolero', 'Toyota Fortuner', 'Renault KWID',
       'Honda Amaze', 'Hyundai Santro', 'Mahindra XUV500',
       'Mahindra KUV100', 'Maruti Ignis', 'Datsun RediGO',
       'Mahindra Scorpio', 'Mahindra Marazzo', 'Ford Aspire', 'Ford Figo',
       'Maruti Vitara', 'Tata Tiago', 'Volkswagen Polo', 'Kia Seltos',
       'Maruti Celerio', 'Datsun GO', 'BMW 5', 'Honda CR-V',
       'Ford Endeavour', 'Mahindra KUV', 'Honda Jazz', 'BMW 3', 'Audi A4',
       'Tata Tigor', 'Maruti Ertiga', 'Tata Safari', 'Mahindra Thar',
       'Tata Hexa', 'Land Rover Rover', 'Maruti Eeco', 'Audi A6',
       'Mercedes-Benz E-Class', 'Audi Q7', 'BMW Z4', 'BMW 6', 'Jaguar XF',
       'BMW X5', 'MG Hector', 'Honda Civic', 'Isuzu D-Max',
       'Porsche Cayenne', 'BMW X1', 'Skoda Rapid', 'Ford Freestyle',
       'Skoda Superb', 'Tata Nexon', 'Mahindra XUV300',
       'Maruti Dzire VXI', 'Volvo S90', 'Honda WR-V', 'Maruti XL6',
       'Renault Triber', 'Lexus ES', 'Jeep Wrangler', 'Toyota Camry',
       'Hyundai Elantra', 'Toyota Yaris', 'Mercedes-Benz GL-Class',
       'BMW 7', 'Maruti S-Presso', 'Maruti Dzire LXI', 'Hyundai Aura',
       'Volvo XC', 'Maserati Ghibli', 'Bentley Continental', 'Honda CR',
       'Nissan Kicks', 'Mercedes-Benz S-Class', 'Hyundai Tucson',
       'Tata Harrier', 'BMW X3', 'Skoda Octavia', 'Jeep Compass',
       'Mercedes-Benz CLS', 'Datsun redi-GO', 'Toyota Glanza',
       'Porsche Macan', 'BMW X4', 'Maruti Dzire ZXI', 'Volvo XC90',
       'Jaguar F-PACE', 'Audi A8', 'ISUZU MUX', 'Ferrari GTC4Lusso',
       'Mercedes-Benz GLS', 'Nissan X-Trail', 'Jaguar XE', 'Volvo XC60',
       'Porsche Panamera', 'Mahindra Alturas', 'Tata Altroz', 'Lexus NX',
       'Kia Carnival', 'Mercedes-AMG C', 'Lexus RX', 'Rolls-Royce Ghost',
       'Maserati Quattroporte', 'Isuzu MUX', 'Force Gurkha'], dtype=object)

In [154]:
df['brand'].value_counts()

brand
Maruti           4992
Hyundai          2982
Honda            1485
Mahindra         1011
Toyota            793
Ford              790
Volkswagen        620
Renault           536
BMW               439
Tata              430
Mercedes-Benz     337
Skoda             334
Audi              192
Datsun            170
Jaguar             59
Land Rover         51
Jeep               41
Kia                32
Porsche            21
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
Maserati            2
ISUZU               2
Ferrari             1
Mercedes-AMG        1
Rolls-Royce         1
Force               1
Name: count, dtype: int64

In [155]:
df.head(5)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [156]:
df['seller_type'].value_counts()

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64

In [157]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64

In [158]:
df['transmission_type'].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [159]:
df['seats'].value_counts()

seats
5    12910
7     1922
8      311
6      127
4       77
9       55
2        7
0        2
Name: count, dtype: int64

In [160]:
df.head(5)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [161]:
df[['vehicle_age','km_driven','mileage','engine','max_power','seats']].corr()

             vehicle_age  km_driven   mileage    engine  max_power     seats
vehicle_age     1.000000   0.333891 -0.257394  0.098965   0.005208  0.030791
km_driven       0.333891   1.000000 -0.105239  0.192885   0.044421  0.192830
mileage        -0.257394  -0.105239  1.000000 -0.632987  -0.533128 -0.440280
engine          0.098965   0.192885 -0.632987  1.000000   0.807368  0.551236
max_power       0.005208   0.044421 -0.533128  0.807368   1.000000  0.172257
seats           0.030791   0.192830 -0.440280  0.551236   0.172257  1.000000

In [162]:
df.drop(['Unnamed: 0','car_name'],axis=1,inplace=True,errors='ignore')

In [163]:
df.head(5)

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [164]:
df['transmission_type'].value_counts()

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

In [165]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df[['brand','model','vehicle_age','km_driven','seller_type','fuel_type','transmission_type','mileage','engine','max_power','seats']]
Y=df['selling_price']

In [167]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42)

In [168]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

In [169]:
OH=OneHotEncoder(drop='first',handle_unknown='infrequent_if_exist')
ST=StandardScaler()
categorical=['model','brand','seller_type','fuel_type','transmission_type']
numeric=['vehicle_age','km_driven','mileage','engine','max_power','seats']

In [170]:
pipe=ColumnTransformer([("OneHotEncoder",OH,categorical),("StandardScaler",ST,numeric)])

In [171]:
X_train=pipe.fit_transform(X_train)
X_test=pipe.transform(X_test)

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [172]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
reg=RandomForestRegressor(n_estimators=100,max_depth=10,random_state=42)

In [ ]:
reg.fit(X_train,Y_train)

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_depth=10, random_state=42)

In [175]:
y_pred=reg.predict(X_test)

In [186]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV

In [179]:
r2=r2_score(Y_test,y_pred,)
mse=mean_squared_error(Y_test,y_pred)
mae=mean_absolute_error(Y_test,y_pred)
print(r2)
print(mse)
print(mae)
print(np.sqrt(mse))

0.8620332983636488
101908035156.01717
156694.1404285062
319230.37943782413

In [180]:
trees=[100,200,300,400,500]
depths=[5,10,15,20]
for tree in trees:
    for depth in depths:
        reg=RandomForestRegressor(n_estimators=tree,max_depth=depth,random_state=42)
        reg.fit(X_train,Y_train)
        y_pred=reg.predict(X_test)
        r2=r2_score(Y_test,y_pred)
        mse=mean_squared_error(Y_test,y_pred)
        mae=mean_absolute_error(Y_test,y_pred)
        print(r2)
        print(mse)
        print(mae)
        print(np.sqrt(mse))
        print()

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8620332983636488
101908035156.01717
156694.1404285062
319230.37943782413

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.9227059661971972
57092639170.92162
107654.65329464343
238940.66035507983

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.9273701697903344
53647461326.50903
101930.6720309706
231619.21622894122

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.9289233252815534
52500235057.23796
102242.38248569568
229129.29768416338

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8594616216378652
103807584243.38927
157096.23329575759
322191.8438498859

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.922769414649348
57045773463.35825
107636.29578974281
238842.57045878202

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.9279223281635482
53239613822.424484
101831.93277982535
230737.1097643907

c:\Users\Aryan Chauhan\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

KeyboardInterrupt:

In [183]:
param={
    "n_estimators":[100,200,300,400,500],
    "max_depth":[10,15,20,25]
}

In [ ]:
Ran=RandomizedSearchCV(reg,param_distributions=param,cv=5,n_jobs=-1)
Ran.fit(X_train,Y_train)

In [ ]:
best_model = Ran.best_estimator_
final_pred = best_model.predict(X_test)
print(r2_score(Y_test, final_pred))

In [ ]:
Ran.best_params_