In [255]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [256]:
df=pd.read_csv("Algerian_forest_fires_dataset_UPDATE.csv",header=1)
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
242,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
243,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
244,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
245,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [257]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    str
 1   month        245 non-null    str
 2   year         245 non-null    str
 3   Temperature  245 non-null    str
 4    RH          245 non-null    str
 5    Ws          245 non-null    str
 6   Rain         245 non-null    str
 7   FFMC         245 non-null    str
 8   DMC          245 non-null    str
 9   DC           245 non-null    str
 10  ISI          245 non-null    str
 11  BUI          245 non-null    str
 12  FWI          245 non-null    str
 13  Classes      244 non-null    str
dtypes: str(14)
memory usage: 27.0 KB

In [258]:
df.columns = df.columns.str.strip()

In [259]:
df["day"]=pd.to_numeric(df["day"],errors="coerce")

In [260]:
df["month"]=pd.to_numeric(df["month"],errors="coerce")

In [261]:
df["year"]=pd.to_numeric(df["year"],errors="coerce")

In [262]:
df["Temperature"]=pd.to_numeric(df["Temperature"],errors="coerce")

In [263]:
df["RH"]=pd.to_numeric(df["RH"],errors="coerce")

In [264]:
df["Ws"]=pd.to_numeric(df["Ws"],errors="coerce")

In [265]:
df["Rain"]=pd.to_numeric(df["Rain"],errors="coerce")

In [266]:
df["FFMC"]=pd.to_numeric(df["FFMC"],errors="coerce")

In [267]:
df["DMC"]=pd.to_numeric(df["DC"],errors="coerce")

In [268]:
df["ISI"]=pd.to_numeric(df["ISI"],errors="coerce")

In [269]:
df["BUI"]=pd.to_numeric(df["BUI"],errors="coerce")

In [270]:
df["FWI"]=pd.to_numeric(df["FWI"],errors="coerce")

In [271]:
df["DC"]=pd.to_numeric(df["DC"],errors="coerce")

In [272]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    float64
 1   month        244 non-null    float64
 2   year         244 non-null    float64
 3   Temperature  244 non-null    float64
 4   RH           244 non-null    float64
 5   Ws           244 non-null    float64
 6   Rain         244 non-null    float64
 7   FFMC         244 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          244 non-null    float64
 11  BUI          244 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      244 non-null    str
dtypes: float64(13), str(1)
memory usage: 27.0 KB

In [273]:
df[df.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Classes
167,14.0,7.0,2012.0,37.0,37.0,18.0,0.2,88.9,NaN,NaN,12.5,10.4,NaN,NaN

In [274]:
df.loc[:122,"Region"]=0
df.loc[122:,"Region"]=1

In [275]:
df.isnull().sum()

day            2
month          2
year           2
Temperature    2
RH             2
Ws             2
Rain           2
FFMC           2
DMC            3
DC             3
ISI            2
BUI            2
FWI            3
Classes        2
Region         0
dtype: int64

In [276]:
df=df.dropna().reset_index(drop=True)

In [277]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Region         0
dtype: int64

In [278]:
df.iloc[[122]]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
122,1.0,6.0,2012.0,32.0,71.0,12.0,0.7,57.1,8.2,8.2,0.6,2.8,0.2,not fire,1.0

In [279]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='str')

In [280]:
#df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC','DMC', 'DC', 'ISI', 'BUI', 'FWI']]=df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC','DMC', 'DC', 'ISI', 'BUI', 'FWI']].astype(int)