In [1]:
import numpy as np
import pandas as pd

In [2]:
d={1:[1,2,3,4,5,6],2:[1,2,3,4,5,6],3:[1,2,3,4,5,6],4:[1,2,3,4,5,6]}
df=pd.DataFrame(d)
df

   1  2  3  4
0  1  1  1  1
1  2  2  2  2
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5
5  6  6  6  6

In [3]:
d={'A':1,'B':2,'C':3}

In [4]:
df1=pd.DataFrame(d,index=['X','Y','Z'])
df1

   A  B  C
X  1  2  3
Y  1  2  3
Z  1  2  3

In [5]:
df1.iloc[1,0]

np.int64(1)

In [6]:
d3={1:[1,2,3,4,5],2:[1,2,3,4,5],3:[1,2,3,4,5]}
df2=pd.DataFrame(d3)
df2

   1  2  3
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5

In [7]:
df2[5]=[3,4,5,6,7]
df2

   1  2  3  5
0  1  1  1  3
1  2  2  2  4
2  3  3  3  5
3  4  4  4  6
4  5  5  5  7

In [8]:
d4={1:[1,2,3,4,5],2:[1,2,3,4,5],3:[1,2,3,4,5],4:[1,2,3,4,5],5:[1,2,3,4,5]}
df3=pd.DataFrame(d4)
df3

   1  2  3  4  5
0  1  1  1  1  1
1  2  2  2  2  2
2  3  3  3  3  3
3  4  4  4  4  4
4  5  5  5  5  5

In [9]:
df3['SUm']=df3.sum(axis=0, numeric_only=True)
df3

   1  2  3  4  5   SUm
0  1  1  1  1  1   NaN
1  2  2  2  2  2  15.0
2  3  3  3  3  3  15.0
3  4  4  4  4  4  15.0
4  5  5  5  5  5  15.0

In [10]:
d5={1:[1,2,3,4,5],2:[1,2,3,4,5],3:[1,2,3,4,5]}
df4=pd.DataFrame(d5)
df4

   1  2  3
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5

In [11]:
df4["Pro"]=df4[1]*df4[2]
df4

   1  2  3  Pro
0  1  1  1    1
1  2  2  2    4
2  3  3  3    9
3  4  4  4   16
4  5  5  5   25

In [12]:
d6={1:[1,np.nan,3,4,5],2:[1,2,3,4,np.nan],3:[np.nan,2,3,4,5]}
df5=pd.DataFrame(d6)
df5

     1    2    3
0  1.0  1.0  NaN
1  NaN  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  4.0
4  5.0  NaN  5.0

In [13]:
df5[2].isnull().sum()

np.int64(1)

In [14]:
df5.fillna(2,inplace=True)
df5

     1    2    3
0  1.0  1.0  2.0
1  2.0  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  4.0
4  5.0  2.0  5.0

In [15]:
d7={1:[1,np.nan,3,4,5],2:[1,2,3,4,np.nan],3:[np.nan,2,3,4,5]}
df6=pd.DataFrame(d7)
df6

     1    2    3
0  1.0  1.0  NaN
1  NaN  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  4.0
4  5.0  NaN  5.0

In [16]:
df6.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [17]:
df2.median()

1    3.0
2    3.0
3    3.0
5    5.0
dtype: float64

In [18]:
d8={1:[1,2,3,4,5],2:[1,2,3,4,5],3:[1,2,3,4,5]}
df7=pd.DataFrame(d8)
df7

   1  2  3
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5

In [19]:
d9={"AB":[1,2,3,4,5],2:[1,2,3,4,5],"CA":[1,2,3,4,5]}
df8=pd.DataFrame(d9)
df8

   AB  2  CA
0   1  1   1
1   2  2   2
2   3  3   3
3   4  4   4
4   5  5   5

In [20]:
df7.merge(df8,how='inner')

   1  2  3  AB  CA
0  1  1  1   1   1
1  2  2  2   2   2
2  3  3  3   3   3
3  4  4  4   4   4
4  5  5  5   5   5

In [21]:
mean=df2.mean()
mean

1    3.0
2    3.0
3    3.0
5    5.0
dtype: float64

In [27]:
df2.flatten(())

AttributeError: 'DataFrame' object has no attribute 'flatten'